site_name: ScratchYG
nav:
  - Главная: index.md
  - Примеры: examples.md
  - Установка: installation.md
  - Методы SDK: 
    - Инициализация: sdk/initialization.md
    - Облачные сохранения: sdk/cloud_saving.md
    - Реклама: sdk/ads.md
    - Оценка игры: sdk/game_rating.md
    - Устройство пользователя: sdk/device_info.md
    - Удаленная конфигурация: sdk/flags.md
    - Серверное время: sdk/server_time.md
  - Упаковка игры: packaging.md
theme:
  name: material
  logo: images/icon.png
  favicon: images/icon.png
  palette:
    - scheme: default
      primary: custom
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      primary: custom
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
extra_javascript:
  - javascripts/scratchblocks.min.js
extra_css:
  - stylesheets/extra.css
